### ISSUE TITLE
Concierge.Controller should not inject plugs

### ISSUE THREAD

**Issue by chrismccord** [progress-engine/concierge.ex#1]
Plugs are made to be explicit, and especially for authentication, order is extremely important, so while `use Concierge.Controller` may be nice for imports or other helpers, the auth plugs themselves should be plugged explicitly, for example:

``` elixir
defmodule MyController do
  use MyApp.Web, :controller

  plug Concierge.Authentication

...
end
```

**Comment by sck-v** [comment]
Hello, Chris

Thanks for pointing out :+1:
